openapi: 3.0.1
info:
  title: Voucher Service
  description: Find list of  Voucher
  version: 1.0.0
servers:
  - url: 'http://localhost/voucher'
x-a127-services:
  add-headers-x-api-key:
    provider: x-headers
    apply:
      pipe: request
      endPoint: target
    options:
      displayName: Add AWS api key header
      headers:
        x-api-key:
          type: string
          default: "random_api_key"
          description: >
            x-api-key header
paths:
  /findVoucher:
    post:
      summary: Find Voucher Details
      description: Find Voucher details
      operationId: findVoucher
      tags:
        - Voucher
      parameters:
        - $ref: '#/components/parameters/ChannelId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetVoucherRequest'
      responses:
        '200':
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVoucherResponse'
              example: {
                "resultStatus": {
                  "status": "SUCCESS",
                  "statusCode": null,
                  "errorCode": null,
                  "errorMessage": null
                },
                "voucher": null
              }
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultStatus'

components:
  schemas:
    GetVoucherRequest:
      type: object
      description: Get Voucher Request
      properties:
        serviceId:
          type: string
          description: Service Id
    GetVoucherResponse:
      type: object
      description: Get Voucher Response
      properties:
        resultStatus:
          $ref: '#/components/schemas/ResultStatus'
        voucher:
          type: array
          description: List of vouchers
          items:
            $ref: '#/components/schemas/Voucher'
    Voucher:
      type: object
      description: Voucher details
      properties:
        number:
          type: string
          description: Voucher Number
        type:
          type: string
          description: Voucher Type
        status:
          type: string
          description: Voucher Status

    ResultStatus:
      type: object
      description: Service Result Status
      required:
        - status
      properties:
        status:
          type: string
          description: Result Status SUCCESS/FAILED
        statusCode:
          type: string
          description: Status Code
        errorCode:
          type: string
          description: Error Code
        errorMessage:
          type: string
          description: Error Message
  parameters:
    ChannelId:
      name: channel-id
      in: header
      description: Channel Id
      schema:
        type: string
        example: 20
